#!/usr/bin/env node
// Captures the current git SHA + commit date and writes them to
// cli/src/build-info.js so they get bundled into the pkg-built binary.
// Runs from package.json before every build target. If git isn't available
// (e.g., shipped tarball without .git/), the file is written with empty
// values and the CLI shows "(dev)".
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const repo = path.resolve(__dirname, '..', '..');

function git(args) {
  try {
    return execSync(`git -C "${repo}" ${args}`, {
      stdio: ['ignore', 'pipe', 'ignore']
    }).toString().trim();
  } catch {
    return '';
  }
}

const sha = git('rev-parse --short HEAD');
const date = git('log -1 --format=%cd --date=short HEAD');
const dirty = git('status --porcelain') ? '+' : '';

const outPath = path.resolve(__dirname, '..', 'src', 'build-info.js');
const content =
  `// Generated by scripts/build-info.js — do not edit. .gitignored.\n` +
  `module.exports = ${JSON.stringify({ sha: sha + dirty, date }, null, 2)};\n`;

fs.writeFileSync(outPath, content);
console.log(`wrote ${path.relative(repo, outPath)}: ${sha || '(no git)'}${dirty} ${date}`);
